//! Minimal from-scratch port of the exact subset of `pygam.LinearGAM` that
//! `lingam.camuv.CAMUV._get_residual` needs:
//! `LinearGAM().fit(X, y)` followed by `.predict(X)`, for the default
//! constructor (`n_splines=20`, `spline_order=3`, `lam=0.6`, `"ps"` basis,
//! `fit_intercept=True`).
//!
//! For a Normal-distribution / identity-link GAM, PIRLS degenerates to a single
//! penalized weighted least-squares solve: the pseudo-data is exactly `y` and the
//! PIRLS weights are exactly the (all-ones, by default) sample weights on every
//! iteration, independent of the current coefficients (verified against real
//! `pygam` — see the unit tests below, whose expected values were generated by
//! running actual `pygam.LinearGAM` on the same inputs). So there is no
//! gridsearch, no randomness, and no real iteration to reproduce — just:
//!
//!  1. build one cubic B-spline basis (`n_splines=20`) per explanatory column
//!     plus a trailing intercept column ([`build_model_matrix`]);
//!  2. build the matching block-diagonal second-difference penalty, scaled by
//!     `lam=0.6` per spline term, zero on the intercept ([`penalty_matrix`]);
//!  3. solve `(BᵀB + sqrt(f64::EPSILON)·I + P) · coef = Bᵀy` with
//!     [`crate::util::solve`] — mathematically equivalent to pygam's QR-then-SVD
//!     solve of the same regularized normal equations (pygam uses that route for
//!     numerical stability against the spline/intercept collinearity that
//!     P-splines are prone to; the normal-equations form was checked to
//!     reproduce pygam's coefficients to ~1e-7 and predictions to ~1e-14 on
//!     synthetic data, well within what `CAMUV`'s independence-test thresholds
//!     need — **provided the regression is well-determined**, i.e. `n` is
//!     comfortably larger than `N_SPLINES * k + 1`. Forming `BᵀB` explicitly
//!     squares the condition number, so for `n` smaller than roughly the
//!     coefficient count the two solves can diverge substantially — not a
//!     concern in practice since CAMUV always regresses on the full dataset
//!     (never a small bootstrap-style subsample; it has no `bootstrap()`), and
//!     causal-discovery sample sizes are almost always far larger than
//!     `N_SPLINES=20` times a handful of explanatory columns. See
//!     `docs/differences.md`.);
//!  4. predict as `modelmat · coef` (identity link, no inversion needed).

use ndarray::{Array1, Array2, ArrayView1, ArrayView2};

const N_SPLINES: usize = 20;
const SPLINE_ORDER: usize = 3;
const LAM: f64 = 0.6;

/// `gen_edge_knots` for `dtype="numerical"`: just `(min(x), max(x))`.
fn edge_knots(x: ArrayView1<f64>) -> (f64, f64) {
    let mut lo = f64::INFINITY;
    let mut hi = f64::NEG_INFINITY;
    for &v in x.iter() {
        if v < lo {
            lo = v;
        }
        if v > hi {
            hi = v;
        }
    }
    (lo, hi)
}

/// `b_spline_basis(x, edge_knots, n_splines=20, spline_order=3, periodic=False)`
/// (`pygam/utils.py:624-770`) — vectorized Cox–de Boor recursion, transliterated
/// as scalar loops (the same arithmetic per point; no reduction/order
/// sensitivity, so this is exact, not just numerically close). Returns an
/// `(n, N_SPLINES)` matrix.
fn b_spline_basis(x: ArrayView1<f64>, (e0, e1): (f64, f64)) -> Array2<f64> {
    let n = x.len();
    let offset = e0;
    let scale = if e1 - e0 == 0.0 { 1.0 } else { e1 - e0 };

    // 1 + n_splines - spline_order uniformly spaced boundary knots on [0, 1].
    let boundary_count = 1 + N_SPLINES - SPLINE_ORDER;
    let boundary_knots: Vec<f64> = (0..boundary_count)
        .map(|i| i as f64 / (boundary_count - 1) as f64)
        .collect();
    let diff = boundary_knots[1] - boundary_knots[0];

    // Rescale x into [0, 1] (linear extrapolation handles points outside), and
    // append two sentinel points (0.0, 1.0) needed to derive the extrapolation
    // gradients — dropped again at the very end.
    let mut xs: Vec<f64> = x.iter().map(|&v| (v - offset) / scale).collect();
    xs.push(0.0);
    xs.push(1.0);
    let n_ext = n + 2;

    let extrap_l: Vec<bool> = xs.iter().map(|&v| v < 0.0).collect();
    let extrap_r: Vec<bool> = xs.iter().map(|&v| v > 1.0).collect();
    let any_extrap_l = extrap_l[..n].iter().any(|&b| b);
    let any_extrap_r = extrap_r[..n].iter().any(|&b| b);

    // Augmented knot vector: `spline_order` padding knots below 0 and above 1,
    // the boundary knots in between; nudge the last knot to be inclusive.
    let aug: Vec<f64> = (1..=SPLINE_ORDER).map(|i| i as f64 * diff).collect();
    let mut aug_knots = Vec::with_capacity(SPLINE_ORDER + boundary_count + SPLINE_ORDER);
    for i in (0..SPLINE_ORDER).rev() {
        aug_knots.push(-aug[i]);
    }
    aug_knots.extend_from_slice(&boundary_knots);
    for &a in &aug {
        aug_knots.push(1.0 + a);
    }
    let last = aug_knots.len() - 1;
    aug_knots[last] += 1e-9;
    let n_knots = aug_knots.len();

    // Order-0 (Haar/indicator) basis over `n_knots - 1` intervals.
    let mut maxi = n_knots - 1;
    let mut bases = Array2::<f64>::zeros((n_ext, maxi));
    for i in 0..n_ext {
        for j in 0..maxi {
            if xs[i] >= aug_knots[j] && xs[i] < aug_knots[j + 1] {
                bases[[i, j]] = 1.0;
            }
        }
    }
    // Force symmetric bases at the two sentinel points (the last appended row,
    // for x=1, mirrors the second-to-last, for x=0).
    for j in 0..maxi {
        bases[[n_ext - 1, j]] = bases[[n_ext - 2, maxi - 1 - j]];
    }

    // Cox-de Boor recursion, elevating order `SPLINE_ORDER` times (m = 2..=SPLINE_ORDER+1).
    // `prev_bases` snapshots the last two rows (the sentinel points) right
    // before the final update — needed for the extrapolation gradient below.
    let mut prev_bases = Array2::<f64>::zeros((2, 0));
    for m in 2..=(SPLINE_ORDER + 1) {
        maxi -= 1;
        let old_width = bases.ncols();
        let mut snap = Array2::<f64>::zeros((2, old_width));
        for j in 0..old_width {
            snap[[0, j]] = bases[[n_ext - 2, j]];
            snap[[1, j]] = bases[[n_ext - 1, j]];
        }
        prev_bases = snap;

        let mut next = Array2::<f64>::zeros((n_ext, maxi));
        for i in 0..n_ext {
            let xi = xs[i];
            for j in 0..maxi {
                let denom_l = aug_knots[m - 1 + j] - aug_knots[j];
                let left = (xi - aug_knots[j]) * bases[[i, j]] / denom_l;
                let denom_r = aug_knots[m + j] - aug_knots[j + 1];
                let right = (aug_knots[m + j] - xi) * bases[[i, j + 1]] / denom_r;
                next[[i, j]] = left + right;
            }
        }
        bases = next;
    }
    debug_assert_eq!(bases.ncols(), N_SPLINES);

    if (any_extrap_l || any_extrap_r) && SPLINE_ORDER > 0 {
        let grad_len = n_knots - SPLINE_ORDER - 1;
        debug_assert_eq!(grad_len, N_SPLINES);
        let mut grads = Array2::<f64>::zeros((2, grad_len));
        for k in 0..grad_len {
            let denom_l = aug_knots[SPLINE_ORDER + k] - aug_knots[k];
            let denom_r = aug_knots[SPLINE_ORDER + 1 + k] - aug_knots[1 + k];
            for row in 0..2 {
                let left = prev_bases[[row, k]] / denom_l;
                let right = prev_bases[[row, k + 1]] / denom_r;
                grads[[row, k]] = SPLINE_ORDER as f64 * (left - right);
            }
        }
        if any_extrap_l {
            for i in 0..n {
                if extrap_l[i] {
                    for k in 0..N_SPLINES {
                        bases[[i, k]] = grads[[0, k]] * xs[i] + bases[[n_ext - 2, k]];
                    }
                }
            }
        }
        if any_extrap_r {
            for i in 0..n {
                if extrap_r[i] {
                    for k in 0..N_SPLINES {
                        bases[[i, k]] = grads[[1, k]] * (xs[i] - 1.0) + bases[[n_ext - 1, k]];
                    }
                }
            }
        }
    }

    bases.slice(ndarray::s![..n, ..]).to_owned()
}

/// Closed-form second-difference P-spline penalty `P = DᵀD`, `D` the
/// `(n-2, n)` matrix with rows `[..., 1, -2, 1, ...]` (matches
/// `pygam.penalties.derivative(n, coef, derivative=2, periodic=False)` exactly;
/// verified numerically against it for several `n`).
fn difference_penalty(n: usize) -> Array2<f64> {
    if n <= 1 {
        return Array2::zeros((n, n));
    }
    let rows = n - 2;
    let mut d = Array2::<f64>::zeros((rows, n));
    for i in 0..rows {
        d[[i, i]] = 1.0;
        d[[i, i + 1]] = -2.0;
        d[[i, i + 2]] = 1.0;
    }
    d.t().dot(&d)
}

/// Model matrix for `k` explanatory columns: `[spline(col_0) | ... | spline(col_{k-1}) | 1]`,
/// shape `(n, N_SPLINES * k + 1)`.
fn build_model_matrix(x: ArrayView2<f64>) -> Array2<f64> {
    let n = x.nrows();
    let k = x.ncols();
    let m = N_SPLINES * k + 1;
    let mut modelmat = Array2::<f64>::zeros((n, m));
    for c in 0..k {
        let col = x.column(c);
        let basis = b_spline_basis(col, edge_knots(col));
        let base = c * N_SPLINES;
        for j in 0..N_SPLINES {
            for i in 0..n {
                modelmat[[i, base + j]] = basis[[i, j]];
            }
        }
    }
    for i in 0..n {
        modelmat[[i, m - 1]] = 1.0;
    }
    modelmat
}

/// Block-diagonal penalty `block_diag(lam·P20, lam·P20, ..., [0])` matching
/// `build_model_matrix`'s column layout: one `lam`-scaled `N_SPLINES` block per
/// explanatory column, then a `1x1` zero block for the intercept.
fn penalty_matrix(k: usize) -> Array2<f64> {
    let m = N_SPLINES * k + 1;
    let mut penalty = Array2::<f64>::zeros((m, m));
    let p = difference_penalty(N_SPLINES);
    for c in 0..k {
        let base = c * N_SPLINES;
        for a in 0..N_SPLINES {
            for b in 0..N_SPLINES {
                penalty[[base + a, base + b]] = LAM * p[[a, b]];
            }
        }
    }
    penalty
}

/// `y - LinearGAM().fit(x_explanatory, y).predict(x_explanatory)` — CAMUV's
/// `_get_residual` when `explanatory_ids` is non-empty. When `x_explanatory` has
/// zero columns, mirrors the Python special case: the "residual" is just `y`
/// unchanged (no regression at all).
pub fn gam_residual(x_explanatory: ArrayView2<f64>, y: ArrayView1<f64>) -> Array1<f64> {
    let k = x_explanatory.ncols();
    if k == 0 {
        return y.to_owned();
    }
    let n = x_explanatory.nrows();
    let m = N_SPLINES * k + 1;

    let modelmat = build_model_matrix(x_explanatory);
    let penalty = penalty_matrix(k);

    let mut ata = modelmat.t().dot(&modelmat);
    let ridge = f64::EPSILON.sqrt();
    for i in 0..m {
        ata[[i, i]] += ridge;
    }
    ata = &ata + &penalty;
    let aty = modelmat.t().dot(&y);

    let coef = crate::util::solve(&ata, &aty).unwrap_or_else(|| {
        // Ridge-regularized system should never be singular in practice; fall
        // back to a slightly stronger ridge if it somehow is (same idiom as
        // `util::linreg_coef`'s fallback).
        let mut ata2 = ata.clone();
        let trace: f64 = (0..m).map(|i| ata2[[i, i]]).sum();
        let extra = (trace / m as f64).max(1.0) * 1e-8;
        for i in 0..m {
            ata2[[i, i]] += extra;
        }
        crate::util::solve(&ata2, &aty).unwrap_or_else(|| Array1::zeros(m))
    });

    let pred = modelmat.dot(&coef);
    let mut resid = y.to_owned();
    resid -= &pred;
    let _ = n; // n only used for clarity/debug_assert above
    resid
}

#[cfg(test)]
mod tests {
    use super::*;
    use ndarray::{Array2, array};

    fn close(a: f64, b: f64, atol: f64) {
        assert!((a - b).abs() < atol, "{a} vs {b} (atol {atol})");
    }

    #[test]
    fn basis_is_partition_of_unity_inside_range() {
        let x = array![-2.0, -1.0, -0.3, 0.0, 0.5, 1.0, 1.7, 2.0];
        let basis = b_spline_basis(x.view(), (-2.0, 2.0));
        for i in 0..x.len() {
            let row_sum: f64 = basis.row(i).sum();
            close(row_sum, 1.0, 1e-9);
        }
    }

    #[test]
    fn difference_penalty_matches_pygam_for_n5() {
        // pygam.penalties.derivative(5, None, derivative=2, periodic=False)
        let expected = array![
            [1.0, -2.0, 1.0, 0.0, 0.0],
            [-2.0, 5.0, -4.0, 1.0, 0.0],
            [1.0, -4.0, 6.0, -4.0, 1.0],
            [0.0, 1.0, -4.0, 5.0, -2.0],
            [0.0, 0.0, 1.0, -2.0, 1.0],
        ];
        let got = difference_penalty(5);
        for i in 0..5 {
            for j in 0..5 {
                close(got[[i, j]], expected[[i, j]], 1e-12);
            }
        }
    }

    /// Single explanatory column, `n=60` samples (comfortably more samples than
    /// the `n_splines+1=21` coefficients — see the module docs and
    /// `docs/differences.md` for why this matters: `pygam`'s QR-then-SVD solve
    /// and this port's normal-equations solve are only guaranteed to agree
    /// closely when the regression is well-determined this way). Reference
    /// `resid` generated by running real `pygam.LinearGAM().fit(X, y)` on this
    /// exact data (see conversation history for the generating script).
    #[test]
    fn one_column_residual_matches_pygam() {
        let x = array![
            0.7294, -1.7847, -1.1186, -1.2625, -1.2964, 1.2484, 1.6934, -0.8937, 1.279, 1.5596,
            0.0519, -1.0201, 1.297, -1.1449, 0.9659, 0.5198, 1.7096, -1.0724, 1.1965, 0.0727,
            -1.0738, -1.3364, -0.0088, 0.3309, -1.2626, -1.9404, -0.1155, 0.913, 1.6744, 0.5021,
            1.6685, 1.4588, -1.1274, 1.4645, 0.923, -0.8885, 1.1882, 1.4609, -0.8022, 0.1082,
            -1.7141, 0.333, -1.0484, 1.0599, -1.3055, -0.749, -1.9421, -1.8698, -0.0132, -0.1267,
            -1.4892, -0.9697, -1.9873, -0.4757, 0.3035, -0.2908, 1.3404, 0.466, -0.9357, 1.2441
        ];
        let y = array![
            0.6393, -1.0051, -0.9153, -0.9759, -1.0344, 1.0167, 1.0144, -0.815, 0.9726, 0.978,
            0.0413, -0.834, 1.0104, -0.8347, 0.9078, 0.4843, 0.9654, -0.8734, 0.9372, 0.0359,
            -0.91, -0.932, 0.0733, 0.3136, -0.9853, -0.9466, -0.165, 0.7777, 1.0158, 0.4772, 1.057,
            1.0013, -0.8792, 0.9869, 0.8632, -0.8372, 0.9125, 0.9353, -0.6776, 0.1505, -1.0155,
            0.4098, -0.8815, 0.8031, -0.9791, -0.6629, -0.9436, -0.8424, 0.0296, -0.0398, -0.9274,
            -0.909, -0.9334, -0.5944, 0.2665, -0.231, 0.9314, 0.4175, -0.7887, 0.9865
        ];
        let expected = [
            -0.02904512736165743,
            -0.04420006282880051,
            -0.00970680469130758,
            -0.023236963636558694,
            -0.07372605590076386,
            0.06060130900733163,
            0.005841378510916373,
            -0.019444636187235464,
            0.009134749542919152,
            -0.02050776289154488,
            -0.03129187482575618,
            0.02860746328796071,
            0.04310047889272961,
            0.0809605878276366,
            0.07180134965282658,
            -0.008427817417188566,
            -0.04429240329829054,
            0.013059254091234207,
            -0.003907203299760131,
            -0.056732740298445786,
            -0.02293411370729248,
            0.03645930546538312,
            0.060426302175395595,
            -0.015204595573272084,
            -0.032611487546825635,
            -0.012614101523733212,
            -0.06801461082306173,
            -0.025548004423517123,
            0.008589639720783193,
            -0.0003704444804779605,
            0.050212721066332344,
            0.011537724799970173,
            0.029829586348933068,
            -0.003400348235950479,
            0.05353046352422042,
            -0.044683076961100965,
            -0.025916827064443426,
            -0.054661533889660996,
            0.06132512195933448,
            0.02410697367568232,
            -0.0451407967724502,
            0.07914384172339417,
            -0.005699082356951046,
            -0.08334925873851062,
            -0.01649334950629533,
            0.04005206396431593,
            -0.009931154870555958,
            0.10447750522836108,
            0.021132267075767132,
            0.06903913264985165,
            0.05497095391598805,
            -0.07154903910686028,
            -0.008179657492838777,
            -0.11415946216912193,
            -0.038068594778066844,
            0.055817183446765534,
            -0.04379431584304472,
            -0.02903004171730844,
            0.030592224186605343,
            0.03152376776149024,
        ];
        let n = x.len();
        let xe = x.into_shape_with_order((n, 1)).unwrap();
        let resid = gam_residual(xe.view(), y.view());
        for i in 0..n {
            close(resid[i], expected[i], 1e-5);
        }
    }

    /// Two explanatory columns, `n=80` samples (more than the `2*20+1=41`
    /// coefficients). Reference `resid` generated by running real
    /// `pygam.LinearGAM().fit(X, y)` on this exact data.
    #[test]
    fn two_column_residual_matches_pygam() {
        let x0 = [
            0.0241, 0.0477, 0.4596, -0.8529, -0.1299, 1.7218, -0.7622, -0.9189, 1.7449, 1.0986,
            -0.8054, -0.191, -0.2596, 0.3415, 0.6227, -1.2253, -0.9918, -1.5475, 0.3701, 1.1114,
            -0.6726, 0.7513, 1.0782, -0.8819, 0.2917, 0.6895, 1.0096, -1.8483, 1.5814, 1.128,
            0.8227, -1.6987, 0.4929, -0.9808, 0.9116, 0.1789, 1.9723, 0.89, -0.4069, 1.3687,
            -1.8404, -0.9212, -0.9447, 0.0042, -0.1874, 1.9118, -0.968, -0.4859, 1.6937, -1.4692,
            -0.7782, -0.984, 0.042, -0.0108, 1.0605, 0.9233, 1.1218, -0.874, 0.4877, -0.9775,
            -0.2138, -0.0821, 0.1081, -0.7264, 1.8687, -1.9161, -1.2768, 0.2719, 1.27, 1.5201,
            -1.094, 1.3357, 1.5429, -0.9782, -1.7716, -0.5024, 1.2092, 1.9719, 1.5639, 1.6435,
        ];
        let x1 = [
            0.2604, 1.8887, 0.2731, 0.218, 0.4402, -1.0165, -0.4357, -0.5999, -0.4885, -1.8377,
            0.8104, 1.5594, 0.4942, 0.3965, 0.0451, -1.7241, -1.6192, -0.8777, -0.6271, 1.8615,
            -1.0549, 0.2907, 0.4677, 1.6444, 0.8732, 1.0792, -0.3588, -0.0601, -1.4218, 0.6215,
            -1.1276, -0.9289, -0.4457, -0.4118, -0.9779, -0.3744, 1.4154, 0.2025, 0.7112, -1.44,
            -0.1615, 1.5406, 1.6524, 1.34, 0.8646, -1.3357, 0.0625, 1.2061, 0.2905, -0.4938,
            0.5798, -1.6599, -0.8806, -0.6168, -0.9661, -1.5401, 1.9889, 1.9987, 0.2808, 0.6807,
            0.3738, 1.1285, -0.6671, 0.2418, -1.5939, -0.2001, 1.6304, 1.2787, -1.9544, -0.2981,
            1.4716, 1.4896, 1.8334, -1.031, 0.999, 0.6797, -0.9777, 0.3936, 0.0592, -0.0476,
        ];
        let y = array![
            0.1031, 0.9452, 0.3477, 0.7269, 0.3678, 2.4275, 0.4, 0.4369, 2.792, 0.2061, 1.0285,
            0.8795, 0.3536, 0.3459, 0.4353, 0.5516, 0.1171, 1.9832, -0.1086, 2.1887, -0.0466,
            0.7371, 1.4313, 1.624, 0.4664, 1.0637, 0.7948, 3.3127, 1.7964, 1.5164, 0.059, 2.4262,
            -0.021, 0.7116, 0.3649, -0.0997, 4.6342, 0.9383, 0.447, 1.186, 3.3057, 1.5831, 1.7036,
            0.6509, 0.415, 2.8896, 0.9868, 0.8519, 3.0804, 1.9686, 0.9047, 0.1809, -0.3616, -0.343,
            0.6285, 0.0959, 2.185, 1.709, 0.4113, 1.2743, 0.2553, 0.5653, -0.2602, 0.6623, 2.7017,
            3.5575, 2.3942, 0.6359, 0.7691, 2.1774, 1.9841, 2.4847, 3.3207, 0.4605, 3.5949, 0.6932,
            1.0479, 4.0772, 2.5313, 2.7366
        ];
        let expected = [
            -0.05840571238528633,
            0.0015053992246958359,
            -0.021450201018993087,
            -0.11243815351536879,
            0.0966104124493331,
            -0.05592370495105925,
            0.038888397255262164,
            -0.09459714646751888,
            -0.02800035295756409,
            -0.09565110881896238,
            0.007610361021291201,
            0.0333706538887828,
            0.004915028758132656,
            0.011284520485160043,
            0.006027697247036334,
            -0.06968149688538572,
            -0.02384199621478754,
            0.00385744731306481,
            0.05756943575382126,
            0.03799978940333837,
            0.01825379194387164,
            0.007382969509607262,
            0.028027446720755522,
            0.03267031300135703,
            -0.031813608211609556,
            0.0687844368591447,
            -0.04203482077735987,
            -0.04857841233037874,
            -0.0028692699396806187,
            -0.06145535526936596,
            -0.05074918297331504,
            -0.007541366396619509,
            -0.047855627653336494,
            -0.025325071873805838,
            0.016887401585514272,
            0.045076868488387226,
            0.0718195923155136,
            0.032193067133332476,
            -0.08508750173820384,
            0.03150574782246629,
            0.02393931538698446,
            -0.024589533823612175,
            -0.0020160556497479387,
            -0.028640078008581815,
            -0.04712793675389754,
            -0.06446314202610148,
            0.02574220144747219,
            0.006146590762981963,
            0.02678352828458941,
            0.048878606820042414,
            0.013118531820337398,
            0.07216812493247254,
            0.049711205362971744,
            -0.05630285752621483,
            -0.017921472085006274,
            0.03335972476026895,
            -0.03291843063756916,
            -0.005359110805904788,
            0.01125228463135075,
            0.010015729597532053,
            -0.016969625412573797,
            -0.0026509617943691888,
            0.042628535986656724,
            -0.002873780277645399,
            0.023357076413657918,
            0.04355505438892493,
            -0.045959558665528366,
            -0.07186264736557979,
            0.07899923923832186,
            -0.0167705321631213,
            0.07010913997385959,
            -0.06596160154309949,
            0.003788749631384203,
            0.03457928777685415,
            -0.0010835592623728019,
            0.08914521647020934,
            0.06023869986197361,
            0.011824403429500308,
            0.014447458761951193,
            0.0207415135451976,
        ];
        let n = x0.len();
        let mut xe = Array2::<f64>::zeros((n, 2));
        for i in 0..n {
            xe[[i, 0]] = x0[i];
            xe[[i, 1]] = x1[i];
        }
        let resid = gam_residual(xe.view(), y.view());
        for i in 0..n {
            close(resid[i], expected[i], 1e-5);
        }
    }

    #[test]
    fn zero_columns_returns_y_unchanged() {
        let y = array![1.0, 2.0, 3.0];
        let xe = Array2::<f64>::zeros((3, 0));
        let resid = gam_residual(xe.view(), y.view());
        assert_eq!(resid.to_vec(), y.to_vec());
    }
}
